# "environment" defaults to "development", so this environment file gets loaded

# Process the tomcat-users template file and install it to the Tomcat server
# Config is empty because we obtain our key/value pairs from environment vars
tomcat-users.erb:
  target: /usr/local/tomcat/conf/tomcat-users.xml
  config: {}

# Process the server template file and install it to the Tomcat server
# Config is empty because we obtain our key/value pairs from environment vars
server.erb:
  target: /usr/local/tomcat/conf/server.xml
  config: {}
  
